### PR TITLE
Create source for fasta parser without biojs-io-parser mixin

### PR DESCRIPTION
**Pull request by Hypercubed**
I want to use the Fasta parser in the browser but the GenericReader (biojs-io-parser) was giving me some issues.  With this change (which is really just splitting index.coffee into two files) I can use the fasta parser without loading biojs-io-parser mixins (using `import Fasta from 'biojs-io-fasta/lib/fasta';` for example).

### CODE REVIEW

**Comment by wilzbach** [comment]
> With this change (which is really just splitting index.coffee into tow files) I can use the fasta parser without loading biojs-io-parser mixins (using import Fasta from 'biojs-io-fasta/lib/fasta'; for example).

Nice. Thanks for the PR. I like it :)

> I want to use the Fasta parser in the browser but the GenericReader (biojs-io-parser) was giving me some issues. 

mind to tell? maybe we can fix them?

**Comment by Hypercubed** [comment]
I don't know!  It works fine with `jspm@latest` (see here: https://github.com/Hypercubed/Project-Chi/blob/master/dataset/example/app/components/examples/biojs/biojs.js) but the browser complains about `tweetnacl@0.13.3` when using `jspm@beta`.  In any event I am pretty sure it is an issue with `XHR` or `request` in jspm v0.17 and nothing to do with biojs-io-parser itself.

**Comment by Hypercubed** [comment]
P.S. Thanks for the quick merge and publish.  Makes life easier on my end.  (and works great!) 😀

**Comment by Hypercubed** [comment]
FYI.... could be related.  https://github.com/jspm/jspm-cli/issues/1599

**Pull request merged**
